.PHONY: scrape train-llm

PYTHON ?= uv run python
SCRAPY_SETTINGS_MODULE ?= scrape_tools.settings
SPIDER ?= fr_wiktionary

HF_TOKEN ?= $(shell pass sabaq_hugging_face_api_token 2>/dev/null | sed -n '1p')
export HF_TOKEN

MONGO_URI ?= mongodb://localhost:27017
MONGO_DB ?= sabaq
RAW_COLLECTION ?= fr_wiktionary_raw
TRAINING_COLLECTION ?= training_fr_wiktionary
MODEL_NAME ?= camembert/camembert-base-wikipedia-4gb
COHESION_MODEL_NAME ?= $(MODEL_NAME)
SPACY_MODEL ?= fr_dep_news_trf
SOURCE_LANGUAGE ?= fr
PIVOT_LANGUAGE ?= hi
METEOR_THRESHOLD ?= 0.7
COHESION_THRESHOLD ?= 0.02
OBJECTIVE_PENALTY_MULTIPLIER ?= 100
OUTPUT_DIR ?= runs/idiom-recognition

scrape:
	SCRAPY_SETTINGS_MODULE=$(SCRAPY_SETTINGS_MODULE) \
	MONGO_URI="$(MONGO_URI)" \
	MONGO_DB="$(MONGO_DB)" \
	MONGO_RAW_COLLECTION="$(RAW_COLLECTION)" \
	MONGO_TRAINING_COLLECTION="$(TRAINING_COLLECTION)" \
	$(PYTHON) -m scrapy crawl $(SPIDER)

train-llm:
	MONGO_URI="$(MONGO_URI)" \
	MONGO_DB="$(MONGO_DB)" \
	TRAINING_COLLECTION="$(TRAINING_COLLECTION)" \
	MODEL_NAME="$(MODEL_NAME)" \
	COHESION_MODEL_NAME="$(COHESION_MODEL_NAME)" \
	SPACY_MODEL="$(SPACY_MODEL)" \
	SOURCE_LANGUAGE="$(SOURCE_LANGUAGE)" \
	PIVOT_LANGUAGE="$(PIVOT_LANGUAGE)" \
	METEOR_THRESHOLD="$(METEOR_THRESHOLD)" \
	COHESION_THRESHOLD="$(COHESION_THRESHOLD)" \
	OBJECTIVE_PENALTY_MULTIPLIER="$(OBJECTIVE_PENALTY_MULTIPLIER)" \
	OUTPUT_DIR="$(OUTPUT_DIR)" \
	$(PYTHON) -m sabaq_llm.train
