.PHONY: scrape train-llm export-hf-dataset

PYTHON ?= uv run python
SCRAPY_SETTINGS_MODULE ?= scrape_tools.settings
SPIDER ?= fr_wiktionary

HF_TOKEN ?= $(shell pass sabaq_hugging_face_api_token 2>/dev/null | sed -n '1p')
export HF_TOKEN

MONGO_URI ?= mongodb://localhost:27017
MONGO_DB ?= sabaq
RAW_COLLECTION ?= fr_wiktionary_raw
TRAINING_COLLECTION ?= training_fr_wiktionary
MODEL_NAME ?= camembert/camembert-base-wikipedia-4gb
COHESION_MODEL_NAME ?= $(MODEL_NAME)
SPACY_MODEL ?= fr_dep_news_trf
SOURCE_LANGUAGE ?= fr
PIVOT_LANGUAGE ?= hi
METEOR_THRESHOLD ?= 0.7
COHESION_THRESHOLD ?= 0.02
OBJECTIVE_PENALTY_MULTIPLIER ?= 100
OUTPUT_DIR ?= runs/idiom-recognition
TRAINING_DATA_SOURCE ?= mongo
HF_DATASET_PATH ?=
HF_DATASET_REPO ?=
HF_DATASET_OUTPUT_DIR ?= runs/hf-training-dataset
TRAIN_RATIO ?= 0.8
VALIDATION_RATIO ?= 0.1
SEED ?= 42
MAX_TRAINING_ROWS ?=
LEARNING_RATE ?= 2e-5
TRAIN_BATCH_SIZE ?= 1
EVAL_BATCH_SIZE ?= 1
NUM_TRAIN_EPOCHS ?= 3
GRADIENT_ACCUMULATION_STEPS ?= 1
WEIGHT_DECAY ?= 0.01
LOGGING_STEPS ?= 10
DISABLE_TQDM ?= 0

scrape:
	SCRAPY_SETTINGS_MODULE=$(SCRAPY_SETTINGS_MODULE) \
	MONGO_URI="$(MONGO_URI)" \
	MONGO_DB="$(MONGO_DB)" \
	MONGO_RAW_COLLECTION="$(RAW_COLLECTION)" \
	MONGO_TRAINING_COLLECTION="$(TRAINING_COLLECTION)" \
	$(PYTHON) -m scrapy crawl $(SPIDER)

train-llm:
	MONGO_URI="$(MONGO_URI)" \
	MONGO_DB="$(MONGO_DB)" \
	TRAINING_COLLECTION="$(TRAINING_COLLECTION)" \
	TRAINING_DATA_SOURCE="$(TRAINING_DATA_SOURCE)" \
	HF_DATASET_PATH="$(HF_DATASET_PATH)" \
	HF_DATASET_REPO="$(HF_DATASET_REPO)" \
	MAX_TRAINING_ROWS="$(MAX_TRAINING_ROWS)" \
	TRAIN_RATIO="$(TRAIN_RATIO)" \
	VALIDATION_RATIO="$(VALIDATION_RATIO)" \
	SEED="$(SEED)" \
	LEARNING_RATE="$(LEARNING_RATE)" \
	TRAIN_BATCH_SIZE="$(TRAIN_BATCH_SIZE)" \
	EVAL_BATCH_SIZE="$(EVAL_BATCH_SIZE)" \
	NUM_TRAIN_EPOCHS="$(NUM_TRAIN_EPOCHS)" \
	GRADIENT_ACCUMULATION_STEPS="$(GRADIENT_ACCUMULATION_STEPS)" \
	WEIGHT_DECAY="$(WEIGHT_DECAY)" \
	LOGGING_STEPS="$(LOGGING_STEPS)" \
	DISABLE_TQDM="$(DISABLE_TQDM)" \
	MODEL_NAME="$(MODEL_NAME)" \
	COHESION_MODEL_NAME="$(COHESION_MODEL_NAME)" \
	SPACY_MODEL="$(SPACY_MODEL)" \
	SOURCE_LANGUAGE="$(SOURCE_LANGUAGE)" \
	PIVOT_LANGUAGE="$(PIVOT_LANGUAGE)" \
	METEOR_THRESHOLD="$(METEOR_THRESHOLD)" \
	COHESION_THRESHOLD="$(COHESION_THRESHOLD)" \
	OBJECTIVE_PENALTY_MULTIPLIER="$(OBJECTIVE_PENALTY_MULTIPLIER)" \
	OUTPUT_DIR="$(OUTPUT_DIR)" \
	$(PYTHON) -m sabaq_llm.train

export-hf-dataset:
	MONGO_URI="$(MONGO_URI)" \
	MONGO_DB="$(MONGO_DB)" \
	TRAINING_COLLECTION="$(TRAINING_COLLECTION)" \
	MAX_TRAINING_ROWS="$(MAX_TRAINING_ROWS)" \
	HF_DATASET_OUTPUT_DIR="$(HF_DATASET_OUTPUT_DIR)" \
	TRAIN_RATIO="$(TRAIN_RATIO)" \
	VALIDATION_RATIO="$(VALIDATION_RATIO)" \
	SEED="$(SEED)" \
	$(PYTHON) -m sabaq_llm.export_dataset
