# Generated by Django 5.2.3 on 2025-06-22 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[
                 ('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='frenchdictionaryentry',
            name='owners',
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(choices=[
                 ('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[], max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('dictionary_entry', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.dictionaryentry')),
            ],
        ),
        migrations.DeleteModel(
            name='ArabicDictionaryEntry',
        ),
        migrations.DeleteModel(
            name='FrenchDictionaryEntry',
        ),
    ]
