# Generated by AI on 2025-01-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_examplesentence_remove_frenchdictionaryentry_owners_and_more'),
    ]

    operations = [
        # Create the validation function
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION validate_definition_source()
            RETURNS TRIGGER AS $$
            DECLARE
                entry_language VARCHAR(2);
            BEGIN
                -- Get the language from the related dictionary entry
                SELECT language INTO entry_language
                FROM api_dictionaryentry
                WHERE id = NEW.dictionary_entry_id;

                -- Validate French sources
                IF entry_language = 'fr' AND NEW.source NOT IN ('wolf_wordnet', 'wiktionary') THEN
                    RAISE EXCEPTION 'Source "%" is not valid for French entries. Valid sources: wolf_wordnet, wiktionary', NEW.source;
                END IF;

                -- Validate Arabic sources
                IF entry_language = 'ar' AND NEW.source NOT IN ('aratools') THEN
                    RAISE EXCEPTION 'Source "%" is not valid for Arabic entries. Valid sources: aratools', NEW.source;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS validate_definition_source() CASCADE;"
        ),

        # Create the trigger
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER definition_source_validation_trigger
                BEFORE INSERT OR UPDATE ON api_definition
                FOR EACH ROW
                EXECUTE FUNCTION validate_definition_source();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS definition_source_validation_trigger ON api_definition;"
        ),
    ]
