# Generated by Django 5.2.3 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_source_language_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
