# Generated by Django 5.2.3 on 2025-07-05 17:32

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_definition_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="created",
            field=models.DateTimeField(default=api.utils.default_now, editable=False),
        ),
        migrations.AddField(
            model_name="definition",
            name="modified",
            field=models.DateTimeField(default=api.utils.default_now),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="created",
            field=models.DateTimeField(default=api.utils.default_now, editable=False),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="modified",
            field=models.DateTimeField(default=api.utils.default_now),
        ),
        migrations.AddField(
            model_name="document",
            name="created",
            field=models.DateTimeField(default=api.utils.default_now, editable=False),
        ),
        migrations.AddField(
            model_name="document",
            name="modified",
            field=models.DateTimeField(default=api.utils.default_now),
        ),
        migrations.AddField(
            model_name="examplesentence",
            name="created",
            field=models.DateTimeField(default=api.utils.default_now, editable=False),
        ),
        migrations.AddField(
            model_name="examplesentence",
            name="modified",
            field=models.DateTimeField(default=api.utils.default_now),
        ),
    ]
