# Generated by Django 5.2.3 on 2025-07-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_definition_created_definition_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="definition",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="examplesentence",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="examplesentence",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
