# Generated by Django 5.2.3 on 2025-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_definition_created_alter_definition_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="curation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
